### PR TITLE
The link is broken, so I've updated it with github pages

### PR DESCRIPTION
**Pull request by AlanApter**
I've created a link for viewing the webpages

### CODE REVIEW

**Comment by Antony74** [comment]
Thanks, I'm thrilled to receive your PR.

Really though my repo should be pointing at my own GitHub pages, not yours.  I guess I didn't know how to do that eleven years ago.  I'd kind of forgotten about this, to be honest.  So it's rather hopelessly out of date.  Perhaps processing.js should be replaced with P5, JQuery with React, and Euclid's formulation of geometry with Hilbert's.

I will try and put the GitHub pages thing in soon, though.

**Comment by AlanApter** [comment]
I'm glad, I've been looking for a library for a foreign language website. Yours still works, which is more than can be said for things with weird build processes, and GitHub Pages was in its infancy when you made this project. 

> Euclid's formulation of geometry with Hilbert's

Very droll, I chuckled

**Comment by Antony74** [comment]
OK, good luck with that.  Happy to discuss related matters further with you.

**Comment by Antony74** [comment]
Closing this for now, thanks again!

**Pull request closed without merging**
